"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { useAuth } from "../context/AuthContext";
import {
  Trash2,
  Edit2,
  ArrowUpRight,
  TrendingUp,
  Clock,
  Star,
  ChevronDown,
  Grid3x3,
  List,
  Search,
  Filter,
  PenSquare,
  X,
  BookOpen,
  Sparkles,
  BarChart3,
} from "lucide-react";
import toast from "react-hot-toast";
import Footer from "../components/Footer";
import apiClient from "../lib/api";

interface Blog {
  _id: string;
  slug?: string;
  title: string;
  description: string;
  // FIX 1: coverImage is now an object, not a flat string
  coverImage?: { url?: string; alt?: string };
  category?: string;
  author?: string;
  date?: string;
  authorId?: string;
  verified?: boolean;
  rating?: number;
  readTime?: number; // added from schema
  createdAt?: string;
  updatedAt?: string;
}

const sortOptions = [
  { label: "All Blogs", value: "default", icon: Grid3x3 },
  { label: "Most Popular", value: "most-viewed", icon: TrendingUp },
  { label: "Most Recent", value: "most-recent", icon: Clock },
];

const BlogPage = () => {
  const [blogs, setBlogs] = useState<Blog[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [sortFilter, setSortFilter] = useState<string>("default");
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");
  const [showFilters, setShowFilters] = useState(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const { user, isAuthenticated } = useAuth();

  useEffect(() => {
    const fetchBlogs = async () => {
      setIsLoading(true);
      setError(null);
      try {
        const { data } = await apiClient.get("/api/v1/posts");
        console.log("data: ", data);
        const postsArray = Array.isArray(data?.items)
          ? data.items
          : Array.isArray(data)
            ? data
            : [];

        const normalized = postsArray.map((post: any, index: number) => ({
          _id: post._id ?? post.id ?? `post-${index}`,
          slug: post.slug ?? post._id ?? post.id,
          title: post.title ?? "Untitled Blog",
          // FIX 2: use post.description directly — it's auto-generated by the schema
          description:
            post.description ??
            "Stay tuned for more insights from Minimalistic Learning.",
          // FIX 1: map coverImage object correctly
          coverImage: post.coverImage ?? null,
          category: post.category ?? "General",
          author:
            post.author?.name ??
            post.author ??
            post.authorName ??
            "Minimalistic Learning",
          authorId: post.authorId ?? post.author?._id ?? post.author?.id,
          date: post.createdAt ?? post.updatedAt ?? new Date().toISOString(),
          verified: post.verified ?? post.published ?? true,
          rating: post.rating ?? post.views ?? 5,
          readTime: post.readTime ?? null, // from schema pre-save hook
          createdAt: post.createdAt,
          updatedAt: post.updatedAt,
        }));

        if (normalized.length) setBlogs(normalized);
      } catch (err) {
        setError("Unable to load blogs from the server.");
        console.error(err);
      } finally {
        setIsLoading(false);
      }
    };
    fetchBlogs();
  }, []);

  // FIX 4: use apiClient instead of raw fetch for consistent auth
  const handleDeleteBlog = async (id: string) => {
    if (!confirm("Are you sure you want to delete this blog?")) return;
    try {
      await apiClient.delete(`/api/v1/posts/${id}`);
      toast.success("Blog deleted successfully");
      setBlogs((prev) => prev.filter((b) => b._id !== id));
    } catch (err: any) {
      console.error(err);
      toast.error(
        err?.response?.data?.message || "An error occurred while deleting.",
      );
    }
  };

  const filteredBlogs = useMemo(() => {
    const filtered = blogs
      .filter(
        (blog) =>
          blog.verified !== false ||
          blog.verified === undefined ||
          blog.verified === null,
      )
      .filter((blog) => {
        const matchesCategory =
          selectedCategory === "All" ||
          blog.category?.toLowerCase() === selectedCategory.toLowerCase();
        const matchesSearch =
          blog.title?.toLowerCase().includes(searchTerm.toLowerCase()) ||
          blog.description?.toLowerCase().includes(searchTerm.toLowerCase());
        return matchesCategory && matchesSearch;
      });

    const sorted = [...filtered];
    if (sortFilter === "most-recent") {
      sorted.sort(
        (a, b) =>
          new Date(b.date ?? 0).getTime() - new Date(a.date ?? 0).getTime(),
      );
    } else if (sortFilter === "most-viewed") {
      sorted.sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0));
    }
    return sorted;
  }, [blogs, searchTerm, selectedCategory, sortFilter]);

  const categories = useMemo(() => {
    const unique = Array.from(
      new Set(blogs.map((b) => b.category).filter(Boolean)),
    ) as string[];
    return ["All", ...unique];
  }, [blogs]);

  const totalCategories = categories.length ? categories.length - 1 : 0;
  const totalAuthors = useMemo(
    () =>
      Array.from(new Set(blogs.map((b) => b.author ?? "Minimalistic Learning")))
        .length,
    [blogs],
  );

  const highlightStats = [
    {
      label: "Published blogs",
      value: blogs.length.toString(),
      meta: "+3 new this week",
      icon: BookOpen,
      color: "from-blue-500 to-blue-600",
    },
    {
      label: "Categories curated",
      value: totalCategories.toString(),
      meta: "Handpicked topics",
      icon: Sparkles,
      color: "from-sky-500 to-sky-600",
    },
    {
      label: "Active mentors",
      value: totalAuthors.toString(),
      meta: "Voices powering the hub",
      icon: TrendingUp,
      color: "from-cyan-500 to-cyan-600",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-sky-50/50 to-cyan-50/50 dark:from-slate-950 dark:via-blue-950/20 dark:to-cyan-950/20 text-slate-800 dark:text-slate-100">
      {/* Hero Section */}
      <section className="relative pt-4 sm:pt-6 pb-12 sm:pb-16 overflow-hidden">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/4 left-1/4 w-48 h-48 sm:w-96 sm:h-96 bg-blue-400/20 rounded-full blur-3xl animate-pulse" />
          <div className="absolute bottom-1/4 right-1/4 w-48 h-48 sm:w-96 sm:h-96 bg-cyan-400/20 rounded-full blur-3xl animate-pulse delay-1000" />
        </div>
        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid gap-6 sm:gap-10 md:grid-cols-[1.2fr_0.8fr] items-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="space-y-4 sm:space-y-6"
            >
              <div className="inline-flex items-center gap-2 rounded-full bg-white/80 dark:bg-slate-900/80 backdrop-blur-sm px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.3em] text-[#2563eb] ring-1 ring-blue-200/50 dark:ring-blue-700/50">
                <Sparkles className="w-3 h-3" /> Blog Hub
              </div>
              <div>
                <h1 className="text-3xl sm:text-5xl lg:text-6xl font-extrabold leading-tight bg-gradient-to-r from-slate-900 via-blue-900 to-slate-900 dark:from-slate-100 dark:via-blue-100 dark:to-slate-100 bg-clip-text text-transparent">
                  Discover Stories,{" "}
                  <span className="bg-gradient-to-r from-blue-600 via-sky-600 to-cyan-600 bg-clip-text text-transparent">
                    Insights & Inspiration
                  </span>
                </h1>
                <p className="mt-4 text-base md:text-lg text-slate-600 dark:text-slate-400 max-w-2xl">
                  Explore curated content from industry experts. Learn, grow,
                  and share your knowledge with the Minimalistic Learning
                  community.
                </p>
              </div>
              <div className="flex flex-wrap gap-2 sm:gap-3">
                {sortOptions.map((option) => {
                  const Icon = option.icon;
                  return (
                    <button
                      key={option.value}
                      onClick={() => setSortFilter(option.value)}
                      className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs sm:text-sm font-semibold transition-all duration-300 ${
                        sortFilter === option.value
                          ? "bg-gradient-to-r from-blue-600 via-sky-600 to-cyan-600 text-white shadow-lg shadow-blue-500/30 scale-105"
                          : "bg-white/80 dark:bg-slate-900/80 text-slate-700 dark:text-slate-300 hover:bg-white border border-slate-200/50"
                      }`}
                    >
                      <Icon className="w-4 h-4" /> {option.label}
                    </button>
                  );
                })}
              </div>
            </motion.div>

            {/* Editor's Card */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="relative rounded-3xl border border-blue-200/50 dark:border-blue-700/50 bg-gradient-to-br from-blue-600 via-sky-600 to-cyan-600 p-8 text-white shadow-2xl ring-2 ring-blue-500/30 overflow-hidden"
            >
              <div className="absolute inset-0 opacity-10">
                <div className="h-full w-full bg-[radial-gradient(circle_at_top,_rgba(255,255,255,0.6),_transparent_60%)]" />
              </div>
              <div className="relative flex flex-col justify-between space-y-6">
                <div>
                  <p className="text-xs uppercase tracking-[0.4em] text-white/70 mb-3">
                    EDITOR&apos;S NOTE
                  </p>
                  <h2 className="text-xl md:text-2xl font-bold leading-relaxed">
                    &ldquo;Consistent storytelling amplifies every
                    community.&rdquo;
                  </h2>
                </div>
                <div className="flex flex-col gap-3">
                  {isAuthenticated && (
                    <Link
                      href="/blog/createblogs"
                      className="inline-flex items-center justify-center gap-2 rounded-xl bg-white/20 backdrop-blur-sm px-5 py-3 text-sm font-semibold text-white transition-all hover:bg-white/30 hover:scale-105"
                    >
                      <PenSquare className="w-4 h-4" /> Publish new blog
                    </Link>
                  )}
                  <Link
                    href="/AdminDashboard/blogsAdmin"
                    className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-[#2563eb] transition-all hover:scale-105"
                  >
                    <BarChart3 className="w-4 h-4" /> Manage library
                  </Link>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mb-8 sm:mb-12">
        <div className="grid gap-4 sm:gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
          {highlightStats.map((stat, index) => {
            const Icon = stat.icon;
            return (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="relative overflow-hidden rounded-3xl border border-slate-200/50 dark:border-slate-700/50 bg-white/95 dark:bg-slate-900/95 p-6 shadow-lg hover:shadow-xl transition-all hover:-translate-y-1"
              >
                <div
                  className={`absolute -right-4 -top-4 h-20 w-20 rounded-full bg-gradient-to-br ${stat.color} opacity-10 blur-2xl`}
                />
                <div className="relative">
                  <div
                    className={`inline-flex items-center justify-center w-12 h-12 rounded-xl bg-gradient-to-br ${stat.color} mb-4`}
                  >
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                  <p className="text-xs font-semibold uppercase tracking-[0.3em] text-slate-400 mb-2">
                    {stat.label}
                  </p>
                  <div className="flex items-baseline gap-3">
                    <span className="text-4xl font-bold text-slate-900 dark:text-slate-100">
                      {stat.value}
                    </span>
                    <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 dark:bg-blue-900/20 px-3 py-1 text-xs font-semibold text-blue-600 dark:text-blue-400">
                      <ArrowUpRight className="w-3 h-3" /> {stat.meta}
                    </span>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* Search and Filter Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mb-8 sm:mb-12">
        <div className="rounded-3xl border border-slate-200/50 dark:border-slate-700/50 bg-white/95 dark:bg-slate-900/95 p-4 sm:p-6 shadow-lg">
          {error && (
            <div className="mb-4 rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-800">
              {error}
            </div>
          )}
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
              <input
                type="text"
                placeholder="Search blogs by title or description..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-12 pr-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-[#2563eb] transition-all"
              />
              {searchTerm && (
                <button
                  onClick={() => setSearchTerm("")}
                  className="absolute right-4 top-1/2 -translate-y-1/2 p-1 rounded-lg hover:bg-slate-100 transition-colors"
                >
                  <X className="w-4 h-4 text-slate-400" />
                </button>
              )}
            </div>
            <div className="flex items-center gap-3">
              <div className="relative">
                <button
                  onClick={() => setShowFilters(!showFilters)}
                  className="inline-flex items-center gap-2 px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm font-semibold hover:bg-slate-50 transition-colors"
                >
                  <Filter className="w-4 h-4" />
                  <span className="hidden sm:inline">Category</span>
                  <ChevronDown
                    className={`w-4 h-4 transition-transform ${showFilters ? "rotate-180" : ""}`}
                  />
                </button>
                <AnimatePresence>
                  {showFilters && (
                    <motion.div
                      initial={{ opacity: 0, y: -10 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -10 }}
                      className="absolute right-0 top-full mt-2 w-64 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-xl p-2 z-50 max-h-96 overflow-y-auto"
                    >
                      {categories.map((category) => (
                        <button
                          key={category}
                          onClick={() => {
                            setSelectedCategory(category || "All");
                            setShowFilters(false);
                          }}
                          className={`w-full text-left px-4 py-2.5 rounded-lg text-sm font-medium transition-colors ${
                            selectedCategory === category
                              ? "bg-gradient-to-r from-blue-600 via-sky-600 to-cyan-600 text-white"
                              : "text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700"
                          }`}
                        >
                          {category}
                        </button>
                      ))}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>

              <div className="flex items-center gap-1 p-1 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                <button
                  onClick={() => setViewMode("grid")}
                  className={`p-2 rounded-lg transition-colors ${viewMode === "grid" ? "bg-white dark:bg-slate-700 text-[#2563eb] shadow-sm" : "text-slate-500"}`}
                >
                  <Grid3x3 className="w-4 h-4" />
                </button>
                <button
                  onClick={() => setViewMode("list")}
                  className={`p-2 rounded-lg transition-colors ${viewMode === "list" ? "bg-white dark:bg-slate-700 text-[#2563eb] shadow-sm" : "text-slate-500"}`}
                >
                  <List className="w-4 h-4" />
                </button>
              </div>

              {isAuthenticated && (
                <Link
                  href="/blog/createblogs"
                  className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 via-sky-600 to-cyan-600 px-5 py-2.5 text-sm font-bold text-white shadow-lg shadow-blue-500/30 transition-all hover:shadow-xl hover:scale-105"
                >
                  <PenSquare className="w-4 h-4" />
                  <span className="hidden sm:inline">Create Blog</span>
                  <span className="sm:hidden">Create</span>
                </Link>
              )}
            </div>
          </div>

          {(searchTerm || selectedCategory !== "All") && (
            <div className="mt-4 pt-4 border-t border-slate-200 dark:border-slate-700 flex flex-wrap gap-2">
              {searchTerm && (
                <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-blue-100 dark:bg-blue-900/20 text-blue-700 text-sm font-medium">
                  Search: &quot;{searchTerm}&quot;
                  <button onClick={() => setSearchTerm("")}>
                    <X className="w-3 h-3" />
                  </button>
                </span>
              )}
              {selectedCategory !== "All" && (
                <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-sky-100 dark:bg-sky-900/20 text-sky-700 text-sm font-medium">
                  Category: {selectedCategory}
                  <button onClick={() => setSelectedCategory("All")}>
                    <X className="w-3 h-3" />
                  </button>
                </span>
              )}
            </div>
          )}
        </div>
      </section>

      {/* Blogs Grid/List */}
      <section className="max-w-7xl mx-auto px-6 pb-24">
        {isLoading ? (
          <div className="flex items-center justify-center py-20">
            <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-200 border-t-blue-600" />
            <span className="ml-3 text-sm text-slate-500">
              Loading blogs...
            </span>
          </div>
        ) : filteredBlogs.length === 0 ? (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="rounded-3xl border border-slate-200 dark:border-slate-700 bg-white/95 dark:bg-slate-900/95 p-16 text-center shadow-lg"
          >
            <div className="max-w-md mx-auto space-y-4">
              <div className="w-16 h-16 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center mx-auto">
                <Search className="w-8 h-8 text-slate-400" />
              </div>
              <h3 className="text-2xl font-bold text-slate-900 dark:text-slate-100">
                No blogs found
              </h3>
              <p className="text-slate-500 dark:text-slate-400">
                Try adjusting your search or filter criteria.
              </p>
              {isAuthenticated && (
                <Link
                  href="/blog/createblogs"
                  className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 via-sky-600 to-cyan-600 px-6 py-3 text-sm font-bold text-white shadow-lg mt-4"
                >
                  <PenSquare className="w-4 h-4" /> Create the first blog
                </Link>
              )}
            </div>
          </motion.div>
        ) : (
          <div
            className={
              viewMode === "grid"
                ? "grid gap-6 md:gap-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3"
                : "space-y-6"
            }
          >
            <AnimatePresence mode="popLayout">
              {filteredBlogs.map((blog, index) => (
                <BlogCard
                  key={blog._id}
                  blog={blog}
                  viewMode={viewMode}
                  index={index}
                  currentUser={user}
                  isAuthenticated={isAuthenticated}
                  onDelete={handleDeleteBlog}
                />
              ))}
            </AnimatePresence>
          </div>
        )}
      </section>

      <Footer />
    </div>
  );
};

// ─── Blog Card ────────────────────────────────────────────────────────────────
function BlogCard({
  blog,
  viewMode,
  index,
  currentUser,
  isAuthenticated,
  onDelete,
}: {
  blog: Blog;
  viewMode: "grid" | "list";
  index: number;
  currentUser: any;
  isAuthenticated: boolean;
  onDelete: (id: string) => void;
}) {
  const isAuthor = useMemo(() => {
    if (!isAuthenticated || !currentUser || !blog) return false;
    if (currentUser.role === "admin" || currentUser.isAdmin) return true;
    if (currentUser.id && currentUser.id === blog.authorId) return true;
    const clientName = (
      currentUser.name ||
      `${currentUser.firstName ?? ""} ${currentUser.lastName ?? ""}`.trim()
    ).toLowerCase();
    const postAuthor = (blog.author || "").toLowerCase();
    if (clientName && postAuthor && clientName === postAuthor) return true;
    if (clientName.includes("manan") && postAuthor === "minimalistic learning")
      return true;
    return false;
  }, [currentUser, isAuthenticated, blog]);

  // FIX 1: helper to safely get image URL from coverImage object
  const imageUrl = blog.coverImage?.url || "/placeholder-blog.jpg";
  const imageAlt = blog.coverImage?.alt || blog.title;

  if (viewMode === "list") {
    return (
      <motion.article
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        exit={{ opacity: 0, x: 20 }}
        transition={{ duration: 0.3, delay: index * 0.05 }}
        // FIX 3: relative needed so absolute edit/delete buttons position correctly
        className="relative group"
      >
        <Link
          href={`/blog/${blog.slug ?? blog._id}`}
          className="flex gap-6 rounded-3xl border border-slate-200/50 dark:border-slate-700/50 bg-white/95 dark:bg-slate-900/95 shadow-lg ring-1 ring-black/5 transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl overflow-hidden"
        >
          <div className="relative w-64 h-48 flex-shrink-0 overflow-hidden">
            <img
              src={imageUrl}
              alt={imageAlt}
              className={`h-full w-full object-cover transition duration-500 group-hover:scale-110 ${!blog.coverImage?.url ? "opacity-50 grayscale" : ""}`}
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
            <div className="absolute top-4 left-4">
              <span className="inline-flex items-center px-3 py-1 rounded-full bg-white/90 dark:bg-slate-900/90 text-xs font-semibold text-[#2563eb]">
                {blog.category || "General"}
              </span>
            </div>
          </div>

          <div className="flex flex-1 flex-col justify-between p-6">
            <div>
              <div className="flex items-center gap-2 mb-3">
                {blog.verified && (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-emerald-100 text-xs font-semibold text-emerald-600">
                    <Star className="w-3 h-3 fill-current" /> Verified
                  </span>
                )}
                {/* readTime from schema */}
                {blog.readTime && (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-blue-50 text-xs font-semibold text-blue-600">
                    <Clock className="w-3 h-3" /> {blog.readTime} min read
                  </span>
                )}
              </div>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-100 mb-3 group-hover:text-[#2563eb] transition-colors">
                {blog.title}
              </h2>
              <p className="text-slate-600 dark:text-slate-400 line-clamp-2 mb-4">
                {blog.description}
              </p>
            </div>
            <div className="flex items-center justify-between text-sm text-slate-500 dark:text-slate-400">
              <div className="flex items-center gap-4">
                <span className="flex items-center gap-1">
                  <Clock className="w-4 h-4" />
                  {blog.date
                    ? new Date(blog.date).toLocaleDateString()
                    : "Recently"}
                </span>
                <span>{blog.author || "Minimalistic Learning"}</span>
              </div>
              <span className="inline-flex items-center gap-2 font-semibold text-[#2563eb] group-hover:gap-3 transition-all">
                Read More <ArrowUpRight className="w-4 h-4" />
              </span>
            </div>
          </div>
        </Link>

        {/* FIX 3: edit/delete outside <Link>, positioned via parent relative */}
        {isAuthor && (
          <div className="absolute top-4 right-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity z-10">
            <Link
              href={`/blog/edit/${blog._id}`}
              className="p-2 rounded-full bg-blue-600 text-white shadow-lg hover:bg-blue-700 transition"
            >
              <Edit2 className="w-4 h-4" />
            </Link>
            <button
              onClick={() => onDelete(blog._id)}
              className="p-2 rounded-full bg-rose-600 text-white shadow-lg hover:bg-rose-700 transition"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        )}
      </motion.article>
    );
  }

  return (
    // FIX 3: relative on article, not inside Link, so buttons render outside the anchor
    <motion.article
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.9 }}
      transition={{ duration: 0.3, delay: index * 0.05 }}
      className="relative group flex h-full flex-col overflow-hidden rounded-3xl border border-slate-200/50 dark:border-slate-700/50 bg-white/95 dark:bg-slate-900/95 shadow-lg ring-1 ring-black/5 transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl"
    >
      <Link
        href={`/blog/${blog.slug ?? blog._id}`}
        className="flex flex-col flex-1"
      >
        <div className="relative h-64 w-full overflow-hidden">
          <img
            src={imageUrl}
            alt={imageAlt}
            className={`h-full w-full object-cover transition duration-500 group-hover:scale-110 ${!blog.coverImage?.url ? "opacity-50 grayscale" : ""}`}
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent" />
          <div className="absolute top-4 left-4 flex items-center gap-2">
            <span className="inline-flex items-center px-3 py-1.5 rounded-full bg-white/90 dark:bg-slate-900/90 text-xs font-bold uppercase tracking-wide text-[#2563eb]">
              {blog.category || "General"}
            </span>
            {blog.verified && (
              <span className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-emerald-500/90 text-xs font-semibold text-white">
                <Star className="w-3 h-3 fill-current" /> Verified
              </span>
            )}
          </div>
          {/* readTime badge on image */}
          {blog.readTime && (
            <div className="absolute bottom-4 left-4">
              <span className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-white/90 dark:bg-slate-900/90 text-xs font-bold text-slate-700">
                <Clock className="w-3 h-3" /> {blog.readTime} min read
              </span>
            </div>
          )}
        </div>

        <div className="flex flex-1 flex-col gap-4 p-6">
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-100 line-clamp-2 group-hover:text-[#2563eb] transition-colors">
            {blog.title}
          </h2>
          <p className="flex-1 text-sm text-slate-600 dark:text-slate-400 line-clamp-3">
            {blog.description}
          </p>
          <div className="flex items-center justify-between pt-4 border-t border-slate-200 dark:border-slate-700">
            <div className="flex items-center gap-3 text-xs text-slate-500 dark:text-slate-400">
              <span className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                {blog.date
                  ? new Date(blog.date).toLocaleDateString()
                  : "Recently"}
              </span>
              <span>•</span>
              <span>{blog.author || "Minimalistic Learning"}</span>
            </div>
            <span className="inline-flex items-center gap-2 text-sm font-semibold text-[#2563eb] group-hover:gap-3 transition-all">
              Read More <ArrowUpRight className="w-4 h-4" />
            </span>
          </div>
        </div>
      </Link>

      {/* FIX 3: outside <Link> entirely, no e.stopPropagation needed */}
      {isAuthor && (
        <div className="absolute top-4 right-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity z-10">
          <Link
            href={`/blog/edit/${blog._id}`}
            className="p-2 rounded-full bg-blue-600 text-white shadow-lg hover:bg-blue-700 transition"
          >
            <Edit2 className="w-4 h-4" />
          </Link>
          <button
            onClick={() => onDelete(blog._id)}
            className="p-2 rounded-full bg-rose-600 text-white shadow-lg hover:bg-rose-700 transition"
          >
            <Trash2 className="w-4 h-4" />
          </button>
        </div>
      )}
    </motion.article>
  );
}

export default BlogPage;
